name: Build and Package LUYViewer for Windows

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.3.x

      - name: Compile LUYViewer for Windows
        run: |
          deno task compile_windows

      - name: Install zip (Windows)
        run: |
          # Use PowerShell to create zip (built-in on Windows)
          
      - name: Create package directory
        run: mkdir package

      - name: Create data directory
        run: mkdir package/data

      - name: Move app and other files into package directory
        run: |
          move LUYViewer.exe package/
          copy LUYViewer_logo.png package/
          copy backend.js package/
          copy config.json package/
          copy detail.js package/
          copy favicon.ico package/
          copy index.html package/
          copy main.css package/
          copy table.js package/

      - name: Create ZIP archive
        run: |
          Compress-Archive -Path package/* -DestinationPath LUYViewer-Windows.zip

      - name: Upload final deployment package
        uses: actions/upload-artifact@v4
        with:
          name: final-deployment-package
          path: LUYViewer-Windows.zip